branch-defaults:
  main:
    environment: Instantutor1013-env
environment-defaults:
  Instantutor1013-env:
    branch: null
    repository: null
global:
  application_name: instantutor-1013
  default_ec2_keyname: instantutor1
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
